name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SolutionPath: source/BenBurgers.Mathematics.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $SolutionPath
    - name: Build (Test)
      run: dotnet build $SolutionPath --configuration Test --no-restore
    - name: Test (x64)
      run: dotnet test $SolutionPath --configuration Test --no-restore --no-build --verbosity normal --arch x64
    #- name: Test (x86)
    #  run: dotnet test $SolutionPath --configuration Test --no-restore --no-build --verbosity normal  --arch x86
    # TODO new workflow for 32-bits environment