name: Logic Release

on:
  pull_request:
    branches:
      - main    
    tags:
      - "*"

jobs:
  BuildAndRelease:
    strategy:
      fail-fast: true
      matrix:
        projectPath:
          - source/BenBurgers.Mathematics.Logic
          - source/BenBurgers.Mathematics.Logic.Expressions
      max-parallel: 1
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      working-directory: ${{ matrix.projectPath }}
      run: dotnet restore
    - name: Build (Test)
      working-directory: ${{ matrix.projectPath }}
      run: dotnet build --configuration Test --no-restore
    - name: Test (x64)
      working-directory: ${{ matrix.projectPath }}
      run: dotnet test --configuration Test --no-restore --no-build --verbosity normal
    - name: Create the package '${{ matrix.projectPath }}'
      working-directory: ${{ matrix.projectPath }}
      run: dotnet pack --configuration Test --no-restore --no-build -p:PackageVersion=${{ github.ref_name }}-preview+${{ github.run_number }}
    - name: Publish the package to GitHub Packages Registry
      working-directory: ${{ matrix.projectPath }}
      run: dotnet nuget push ./bin/Test/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/benburgers/index.json